### ISSUE TITLE
How to fix that error?

### ISSUE THREAD

**Issue by Bana93** [stewartiee/Steam-OpenID--MyBB-#33]
Fatal error: Uncaught exception 'ErrorException' with message 'No OpenID Server found at http://steamcommunity.com/openid' in /membri/guildofgamer/Forum/inc/class_lightopenid.php:515 Stack trace: #0 /membri/guildofgamer/Forum/inc/class_lightopenid.php(648): LightOpenID->discover('http://steamcom...') #1 /membri/guildofgamer/Forum/inc/plugins/steamlogin.php(275): LightOpenID->authUrl() #2 /membri/guildofgamer/Forum/inc/plugins/steamlogin.php(301): steam_redirect() #3 /membri/guildofgamer/Forum/inc/class_plugins.php(101): steam_output_to_misc('') #4 /membri/guildofgamer/Forum/misc.php(24): pluginSystem->run_hooks('misc_start') #5 {main} thrown in /membri/guildofgamer/Forum/inc/class_lightopenid.php on line 515

**Comment by WillMorrow** [comment]
It is your host!
I had the same problem, are you using 000webhost.com?

**Comment by NikolajSimonsson** [comment]
Planeguy I am using 000webhost.com can you please help

**Comment by WillMorrow** [comment]
Sorry for late reply, but I would recommend using [SerenityServers](https://billing.serenityservers.net/aff.php?aff=200)
There is a monthly payment but it is minimal!
